<?php

namespace Database\Factories;

use App\Enums\CategoryType;
use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Category>
 */
class CategoryFactory extends Factory
{
    protected $model = Category::class;

    public function definition(): array
    {
        $name = Str::title(rtrim($this->faker->unique()->sentence(2), '.'));

        return [
            'name' => $name,
            'slug' => null, // generated by the model saving hook
            'type' => CategoryType::Book->value,
        ];
    }

    public function book(): static
    {
        return $this->state(fn () => ['type' => CategoryType::Book->value]);
    }

    public function journal(): static
    {
        return $this->state(fn () => ['type' => CategoryType::Journal->value]);
    }

    public function article(): static
    {
        return $this->state(fn () => ['type' => CategoryType::Article->value]);
    }
}
